branch-defaults:
  default:
    environment: career-exchange-portal
    group_suffix: null
  master:
    environment: careerexchange-dev
    group_suffix: null
commands:
  01_install_pip:
    command: sudo easy_install pip
global:
  application_name: career.exchange
  branch: null
  default_ec2_keyname: evan-key-pair
  default_platform: PHP 7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
packages:
  apt-get:
    poppler-utils: []
    python-setuptools: []
